const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.NinePatch,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Plugins.Touch,
		C3.Plugins.Photon,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Tilemap,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Photon.Acts.requestLobbyStats,
		C3.Plugins.Photon.Cnds.onLobbyStats,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Photon.Exps.RoomCount,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Photon.Exps.RoomPlayerCount,
		C3.Plugins.Photon.Exps.RoomNameAt,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Photon.Exps.RoomMaxPlayers,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Photon.Acts.setMyRoomMaxPlayers,
		C3.Plugins.Photon.Acts.createRoom,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Photon.Acts.joinRoom,
		C3.Plugins.Photon.Cnds.onJoinRoom,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Photon.Cnds.onError,
		C3.Plugins.Photon.Cnds.isInLobby,
		C3.Plugins.Photon.Cnds.isConnectedToMaster,
		C3.Plugins.Photon.Cnds.isConnectedToNameServer,
		C3.Plugins.Photon.Cnds.isJoinedToRoom,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Photon.Acts.disconnect,
		C3.Plugins.Photon.Cnds.onDisconnected,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Photon.Acts.leaveRoom,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Photon.Exps.MyActorNr,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Photon.Exps.ActorNameByNr,
		C3.Plugins.Photon.Acts.raiseEvent,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Photon.Cnds.onEvent,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Photon.Exps.EventData,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Photon.Exps.ActorNr,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Behaviors.MoveTo.Exps.MovingAngle,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.XAt,
		C3.Plugins.Touch.Exps.YAt,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetPosToObject,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.RemoveLayer,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Photon.Exps.MasterActorNr,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Acts.Drop,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.Text.Exps.Count,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Text.Exps.UID,
		C3.Plugins.Text.Cnds.OnDestroyed,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Photon.Acts.setMyActorName,
		C3.Plugins.Photon.Acts.connect,
		C3.Plugins.Photon.Cnds.onJoinedLobby,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Photon.Exps.StateString,
		C3.Plugins.Photon.Exps.ErrorMessage,
		C3.Plugins.Photon.Exps.MyRoomName,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Синусоид: 0},
	{Поворот: 0},
	{ИндикаторЗагрузки: 0},
	{Затемнение: 0},
	{КнопкаСоздатьНовуюКомнату: 0},
	{roomName: 0},
	{ПанельИнфоКомнаты: 0},
	{КнопкаПодключение: 0},
	{ВводТекста: 0},
	{ПанельСпискаКомнат: 0},
	{Текст2: 0},
	{текстФотонИнфо: 0},
	{Type: 0},
	{Прикрепить: 0},
	{Admin_button: 0},
	{ДвижениеК: 0},
	{admin_panel_retractable: 0},
	{Touch: 0},
	{Photon: 0},
	{dialog_text: 0},
	{nickname_text: 0},
	{ТекстИмяКомнаты: 0},
	{ТекстИнфоКомнаты: 0},
	{ТекстКоличествоКомнат: 0},
	{ТекстМоёИмя: 0},
	{Угасание: 0},
	{NotificationUserText: 0},
	{ТекстНаЗемле: 0},
	{Back: 0},
	{Back2: 0},
	{Joystick: 0},
	{Перетаскивание: 0},
	{Joystick2: 0},
	{User_button: 0},
	{ИконкаСмайлика: 0},
	{КнопкаОтключения: 0},
	{level: 0},
	{Solid: 0},
	{Мигание: 0},
	{Door: 0},
	{Value: 0},
	{description: 0},
	{location_9patch: 0},
	{Nr: 0},
	{actual_value: 0},
	{actual_level: 0},
	{head_skin: 0},
	{face_skin: 0},
	{down_skin: 0},
	{СледитьЗа: 0},
	{Платформер: 0},
	{Player: 0},
	{room_9patch: 0},
	{Твердый: 0},
	{WordStone: 0},
	{КартаТайлов: 0},
	{КартаТайлов2: 0},
	{Твёрдый: 0},
	{КартаТайлов3: 0},
	{Смайлик: 0},
	{Твинанимация: 0},
	{ПредметДляВыброса: 0},
	{location_9patch2: 0},
	{Спрайт2: 0},
	{SkinUp: 0},
	{type: 0},
	{Влево: 0},
	{Вправо: 0},
	{SkinDown: 0},
	{PlayerDown: 0},
	{SkinHead: 0},
	{PlayerHead: 0},
	{PlayerFace: 0},
	{Текст: 0},
	{myHead: 0},
	{myFace: 0},
	{myDown: 0},
	{НомерСвободнойКомнаты: 0},
	{счётчикПроверокПодключения: 0},
	{is_view_all: 0},
	{is_view_all_names: 0},
	{остаток_действий: 0},
	{КоличествоТайловНаМакетеПоВысоте: 0},
	{КоличествоТайловНаМакетеПоШирине: 0},
	{current_level: 0},
	{random_dialog: 0},
	{Переменная1: 0},
	{notification_text: 0},
	{notification_count: 0},
	{myName: 0}
];

self.InstanceType = {
	ИндикаторЗагрузки: class extends self.ISpriteInstance {},
	Затемнение: class extends self.ISpriteInstance {},
	КнопкаСоздатьНовуюКомнату: class extends self.ISpriteInstance {},
	ПанельИнфоКомнаты: class extends self.IWorldInstance {},
	КнопкаПодключение: class extends self.ISpriteInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	ПанельСпискаКомнат: class extends self.IWorldInstance {},
	Текст2: class extends self.ITextInstance {},
	текстФотонИнфо: class extends self.ITextInstance {},
	Admin_button: class extends self.ISpriteInstance {},
	admin_panel_retractable: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Photon: class extends self.IInstance {},
	dialog_text: class extends self.ITextInstance {},
	nickname_text: class extends self.ITextInstance {},
	ТекстИмяКомнаты: class extends self.ITextInstance {},
	ТекстИнфоКомнаты: class extends self.ITextInstance {},
	ТекстКоличествоКомнат: class extends self.ITextInstance {},
	ТекстМоёИмя: class extends self.ITextInstance {},
	NotificationUserText: class extends self.ITextInstance {},
	ТекстНаЗемле: class extends self.ITextInstance {},
	Back: class extends self.ISpriteInstance {},
	Back2: class extends self.ISpriteInstance {},
	Joystick: class extends self.ISpriteInstance {},
	Joystick2: class extends self.ISpriteInstance {},
	User_button: class extends self.ISpriteInstance {},
	ИконкаСмайлика: class extends self.ISpriteInstance {},
	КнопкаОтключения: class extends self.ISpriteInstance {},
	Door: class extends self.ISpriteInstance {},
	location_9patch: class extends self.IWorldInstance {},
	Player: class extends self.ISpriteInstance {},
	room_9patch: class extends self.IWorldInstance {},
	WordStone: class extends self.ISpriteInstance {},
	КартаТайлов: class extends self.ITilemapInstance {},
	КартаТайлов2: class extends self.ITilemapInstance {},
	КартаТайлов3: class extends self.ITilemapInstance {},
	Смайлик: class extends self.ISpriteInstance {},
	ПредметДляВыброса: class extends self.ISpriteInstance {},
	location_9patch2: class extends self.IWorldInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	SkinUp: class extends self.ISpriteInstance {},
	Влево: class extends self.ISpriteInstance {},
	Вправо: class extends self.ISpriteInstance {},
	SkinDown: class extends self.ISpriteInstance {},
	PlayerDown: class extends self.ISpriteInstance {},
	SkinHead: class extends self.ISpriteInstance {},
	PlayerHead: class extends self.ISpriteInstance {},
	PlayerFace: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {}
}